config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root    'static_pages#home'   
  get     '/help',              to: 'static_pages#help'
  get     '/about',             to: 'static_pages#about'
  get     '/contact',           to: 'static_pages#contact'
  get     '/signup',            to: 'users#new'
  post    '/signup',            to: 'users#create'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  patch   '/notes/:id',         to: 'notes#update'
  resources :users
  resources :notes,             only: [:create, :destroy, :edit]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @note = current_user.notes.build
      @note_items = current_user.get_notes_user.filter(params[:filter_status]).search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:page], :per_page => 3)
      #respond_to do |format|
        #format.html { render 'home'}
        #format.js { render :partial => @note_items, :formats => [:html]} 
        #format.js {render :layout=>false}
      #end
    end
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.slim
- provide(:title, "About") 
h1 About
p 
  | This is the application for making 
  a<> href='https://bitbucket.org/Michael_Trofimov/usernotes/' target='_blank' User notes 
  |, save, edit and remove them. For users there is a login and authentication system.

app/views/static_pages/contact.html.slim
- provide(:title, 'Contact')
h1 Contact
p
  | You can contact about me at the 
  = mail_to "valeo256@gmail.com", " my email"

app/views/static_pages/help.html.slim
- provide(:title, "Help")
h1 Help
p
  | To get help on this app by 
  = link_to "contacting", contact_path
  |  me

app/views/static_pages/home.html.slim
- if logged_in?
  div class="row"
    aside class="col-md-4"
      section class="user_info"
        = render 'shared/user_info'
      section class="note_form"
        = render 'shared/note_form'
    aside class="col-md-8"
      = render 'shared/notes_form'
- else
  div class="center"
    h1 Welcome to 
    = link_to image_tag("UserNotes.png", alt: "User Notes logo"),
            'https://bitbucket.org/Michael_Trofimov/usernotes/'

    h2 This is the home page for the application in which user can writing and stored itself notes.
    = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"