config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root    'static_pages#home'   
  get     '/help',              to: 'static_pages#help'
  get     '/about',             to: 'static_pages#about'
  get     '/contact',           to: 'static_pages#contact'
  get     '/signup',            to: 'users#new'
  post    '/signup',            to: 'users#create'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  patch   '/notes/:id',         to: 'notes#update'
  resources :users
  resources :notes,             only: [:create, :destroy, :edit]
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :note_status
  #default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :note_status_id, presence: true
  validates :title, presence: true, length: { maximum: 80 }
  validates :content, presence: true, length: { maximum: 140 }

  def self.search(search)
    if search
      where("title LIKE :search OR content LIKE :search", search: "%#{search}%")
    else
      all
    end
  end

  def self.filter(filter_value)
    if filter_value
      where("note_status_id = ?", filter_value)
    else
      all
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy, :edit]
    before_action :correct_user,   only: [:destroy, :edit]

    def create
      @note = current_user.notes.build(note_params)
      if @note.save
        flash[:success] = "Note created!"
        redirect_to root_url
      else
        @note_items = []
        render 'static_pages/home'
      end
    end

    def edit
      render 'notes/edit'
    end

    def update
      @note = Note.find(params[:id])
    if @note.update_attributes(note_params)
      flash[:success] = "Note updated"
      redirect_to request.referrer || root_url
    else
      render 'edit'
    end
  end
    
    def destroy
      @note.destroy
      flash[:success] = "Note deleted"
      redirect_to request.referrer || root_url
    end
    
      private
    
        def note_params
          params.require(:note).permit(:title, :content, :note_status_id)
        end

        def correct_user
          @note = current_user.notes.find_by(id: params[:id])
          redirect_to root_url if @note.nil?
        end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.slim
li id="note-#{note.id}"
  //= link_to gravatar_for(note.user, size: 50), note.user
  //span class="user"
    = link_to note.user.name, note.user 
  span class="title" 
    | Title: 
    = note.title
  span class="content"
    | Status:  
    = note.note_status_id? && NoteStatus.exists?(note.note_status_id) ? NoteStatus.find(note.note_status_id).status : 'Status not found'
  span class="content"
    = note.content
  span class="timestamp"
    Posted 
    = time_ago_in_words(note.created_at)
    |&nbsp;ago.
    - if current_user?(note.user)
      = link_to " delete", note, method: :delete,
                                       data: { confirm: "You sure?" }
      = link_to " edit", edit_note_path(note), method: :get

app/views/notes/edit.html.slim
- if logged_in?
  div class="row"
    aside class="col-md-4"
      section class="user_info"
        = render 'shared/user_info'
      section class="note_form"
        = render 'shared/note_form'
    aside class="col-md-8"
      ol class="notes"
        li
          span class="title" 
            | Title: 
            =@note.title
          span class="content"
            | Status:  
            = @note.note_status_id? && NoteStatus.exists?(@note.note_status_id) ? NoteStatus.find(@note.note_status_id).status : 'Status not found'
          span class="content"
            = @note.content
          span class="timestamp"
            Posted 
            = time_ago_in_words(@note.created_at)
            |&nbsp;ago.