config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root    'static_pages#home'   
  get     '/help',              to: 'static_pages#help'
  get     '/about',             to: 'static_pages#about'
  get     '/contact',           to: 'static_pages#contact'
  get     '/signup',            to: 'users#new'
  post    '/signup',            to: 'users#create'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  patch   '/notes/:id',         to: 'notes#update'
  resources :users
  resources :notes,             only: [:create, :destroy, :edit]
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    a<> href='https://bitbucket.org/Michael_Trofimov/usernotes/' The User Notes
    a<> href='https://www.linkedin.com/in/mikhail-trofimov-5621488b' by Michael Trofimov
  nav
    ul
      li = link_to "About",   about_path
      li = link_to "Contact", contact_path

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
  div.container
        = link_to "user notes", root_path, id: "logo"
        nav
          ul class="nav navbar-nav navbar-right"
            li = link_to "Home",    root_path
            li = link_to "Help",    help_path
            - if logged_in?
              li = link_to "Users", users_path
              li class="dropdown"
                a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                  |Account
                  b class="caret"
                ul class="dropdown-menu"
                  li = link_to "Profile", current_user
                  li = link_to "Settings", edit_user_path(current_user)
                  li class="divider"
                  li = link_to "Log out", logout_path, method: :delete
            - else
              li = link_to "Log in", login_path

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  javascript: src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">  

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    = render "layouts/shim"
  body
    = render 'layouts/header'
    div.container
      - flash.each do |message_type, message|
        div class="alert alert-#{message_type}" = message
      == yield
      = render "layouts/footer"
    = debug(params) if Rails.env.development?